### ISSUE TITLE
Top flag is ignored when set to false

### ISSUE THREAD

**Issue by morisoinc** [ejprok/colorful_safe_area#3]
On SafeArea, setting one of the directions (`left`, `top`, `right`, `bottom`) to `false` means that the safe padding will not be set to that particular direction. This is the result if we set `top` to `false`:

<img width="435" alt="Screen Shot 2020-09-24 at 16 58 53" src="https://user-images.githubusercontent.com/64343733/94193912-55198f80-fe87-11ea-9d90-07da8b602905.png">

On ColorfulSafeArea, instead, it still applies the padding. The only thing it doesn't do is to paint the background. Here's what happens when setting the `top` parameter to `false`:

<img width="425" alt="Screen Shot 2020-09-24 at 16 57 55" src="https://user-images.githubusercontent.com/64343733/94193972-69f62300-fe87-11ea-9eb1-0788037035ac.png">

(_please note that the white dots are part of a custom background I have in the app_)

It should be possible to ignore a padding, shouldn't it? If so, we can have two flags for each direction: one for painting or not, and another one for ignoring the padding or not.

**Comment by ejprok** [comment]
Do you have any example code that can reproduce this behavior?

**Comment by morisoinc** [comment]
Yes, I do have some example code. This is for the `SafeArea`, with the `top` flag set to `false`:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        top: false,
        child: Scaffold(
          body: Container(
            color: Colors.yellow,
          ),
        ),
      ),
    );
  }
}
```

This is its output, with `top` padding not applied, only the `bottom` which defaults to `true`:

<img src="https://user-images.githubusercontent.com/64343733/94287647-f4449280-ff2c-11ea-95f4-a3dc70fecb98.png" alt="drawing" width="200"/>

Now this is the code using `ColorfulSafeArea` instead of `SafeArea`, with `top` also set to `false`, and `color` set to `red`:

```
import 'package:colorful_safe_area/colorful_safe_area.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ColorfulSafeArea(
        top: false,
        color: Colors.red,
        child: Scaffold(
          body: Container(
            color: Colors.yellow,
          ),
        ),
      ),
    );
  }
}
```

You can see that the `top` flag actually disabled the red color being drawn instead of disabling the padding: 

<img src="https://user-images.githubusercontent.com/64343733/94288340-ada36800-ff2d-11ea-83b9-cf8be3ac7b98.png" alt="drawing" width="200"/>

**Comment by ejprok** [comment]
This is definitely a bug, I have a fix that I'll release after a bit of testing. Thanks for finding it.  In the meantime, if you add this line to your ColorfulSafeArea widget, you will have the desired behavior.


`
overflowRules: OverflowRules.only(top: true),
`

**Comment by morisoinc** [comment]
Wow thanks for the quick responses! I'm trying some combinations with `overflowRules` to match what I expect. Thanks!

**Comment by ejprok** [comment]
Version 0.2.1 is released and should address this issue.
