### ISSUE TITLE
Null safety support 

### ISSUE THREAD

**Issue by leynier** [ejprok/colorful_safe_area#5]
I will make a PR with null safety support implementation

**Comment by MagnusJohansson** [comment]
@leynier Did you manage to implement null safety support?

**Comment by mixable** [comment]
Null safety support would be great!

**Comment by rafaelmaeuer** [comment]
Any news on null safety support? @leynier what happened to your plan? @ejprok any roadmaps for this?

**Comment by leynier** [comment]
@MagnusJohansson @mixable @rafaelmaeuer hi guys, the pull request with null safety support is done.

**Comment by renntbenrennt** [comment]
@ejprok please review it, thanks!

**Comment by ejprok** [comment]
PR merged
